
/******************************************************************************
*                                                       *
*   Copyright (C) Microsoft. All rights reserved.   *
*                                                       *
*******************************************************************************/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("product", Namespace = "", IsNullable = false)]
public partial class productType
{

    private string productGuidField;

    private string productImageField;

    private string productTitleField;

    private string productDescriptionField;

    private string productPriceField;

    private agentSkillType[] agentSkillsListField;

    /// <remarks/>
    public string productGuid
    {
        get
        {
            return this.productGuidField;
        }
        set
        {
            this.productGuidField = value;
        }
    }

    /// <remarks/>
    public string productImage
    {
        get
        {
            return this.productImageField;
        }
        set
        {
            this.productImageField = value;
        }
    }

    /// <remarks/>
    public string productTitle
    {
        get
        {
            return this.productTitleField;
        }
        set
        {
            this.productTitleField = value;
        }
    }

    /// <remarks/>
    public string productDescription
    {
        get
        {
            return this.productDescriptionField;
        }
        set
        {
            this.productDescriptionField = value;
        }
    }

    /// <remarks/>
    public string productPrice
    {
        get
        {
            return this.productPriceField;
        }
        set
        {
            this.productPriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("agentSkill", IsNullable = false)]
    public agentSkillType[] agentSkillsList
    {
        get
        {
            return this.agentSkillsListField;
        }
        set
        {
            this.agentSkillsListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class agentSkillType
{

    private string nameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class participantType
{

    private string uriField;

    private string[] mediatypesField;

    private string displaynameField;

    private bool iscustomerField;

    public participantType()
    {
        this.iscustomerField = false;
    }

    /// <remarks/>
    public string uri
    {
        get
        {
            return this.uriField;
        }
        set
        {
            this.uriField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("media-types")]
    [System.Xml.Serialization.XmlArrayItemAttribute("media-type", IsNullable = false)]
    public string[] mediatypes
    {
        get
        {
            return this.mediatypesField;
        }
        set
        {
            this.mediatypesField = value;
        }
    }

    /// <remarks/>
    public string displayname
    {
        get
        {
            return this.displaynameField;
        }
        set
        {
            this.displaynameField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool iscustomer
    {
        get
        {
            return this.iscustomerField;
        }
        set
        {
            this.iscustomerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class agentType
{

    private string uriField;

    private string displaynameField;

    private string statusField;

    private string statuschangedtimeField;

    private string[] mediatypesField;

    /// <remarks/>
    public string uri
    {
        get
        {
            return this.uriField;
        }
        set
        {
            this.uriField = value;
        }
    }

    /// <remarks/>
    public string displayname
    {
        get
        {
            return this.displaynameField;
        }
        set
        {
            this.displaynameField = value;
        }
    }

    /// <remarks/>
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("status-changed-time")]
    public string statuschangedtime
    {
        get
        {
            return this.statuschangedtimeField;
        }
        set
        {
            this.statuschangedtimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("media-types")]
    [System.Xml.Serialization.XmlArrayItemAttribute("media-type", IsNullable = false)]
    public string[] mediatypes
    {
        get
        {
            return this.mediatypesField;
        }
        set
        {
            this.mediatypesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class whisperType
{

    private string uriField;

    /// <remarks/>
    public string uri
    {
        get
        {
            return this.uriField;
        }
        set
        {
            this.uriField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class escalateType
{

    private agentSkillType[] agentSkillsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("agentSkill", IsNullable = false)]
    public agentSkillType[] agentSkills
    {
        get
        {
            return this.agentSkillsField;
        }
        set
        {
            this.agentSkillsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "terminate-monitoring-sessionType")]
public partial class terminatemonitoringsessionType
{

    private string sessionIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sessionId
    {
        get
        {
            return this.sessionIdField;
        }
        set
        {
            this.sessionIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "start-monitoring-sessionType")]
public partial class startmonitoringsessionType
{

    private string uriField;

    private string sessionIdField;

    /// <remarks/>
    public string uri
    {
        get
        {
            return this.uriField;
        }
        set
        {
            this.uriField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sessionId
    {
        get
        {
            return this.sessionIdField;
        }
        set
        {
            this.sessionIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class skillType
{

    private string[] skillValuesField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("skillValue", IsNullable = false)]
    public string[] skillValues
    {
        get
        {
            return this.skillValuesField;
        }
        set
        {
            this.skillValuesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("agent-dashboard-init-data", Namespace = "", IsNullable = false)]
public partial class agentDashboardInitType
{

    private productType productField;

    private skillType[] skillsField;

    /// <remarks/>
    public productType product
    {
        get
        {
            return this.productField;
        }
        set
        {
            this.productField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("skill", IsNullable = false)]
    public skillType[] skills
    {
        get
        {
            return this.skillsField;
        }
        set
        {
            this.skillsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("request", Namespace = "", IsNullable = false)]
public partial class requestType
{

    private object holdField;

    private object retrieveField;

    private object bargeinField;

    private escalateType escalateField;

    private whisperType whisperField;

    private startmonitoringsessionType startmonitoringsessionField;

    private terminatemonitoringsessionType terminatemonitoringsessionField;

    private int requestIdField;

    private string sessionIdField;

    /// <remarks/>
    public object hold
    {
        get
        {
            return this.holdField;
        }
        set
        {
            this.holdField = value;
        }
    }

    /// <remarks/>
    public object retrieve
    {
        get
        {
            return this.retrieveField;
        }
        set
        {
            this.retrieveField = value;
        }
    }

    /// <remarks/>
    public object bargein
    {
        get
        {
            return this.bargeinField;
        }
        set
        {
            this.bargeinField = value;
        }
    }

    /// <remarks/>
    public escalateType escalate
    {
        get
        {
            return this.escalateField;
        }
        set
        {
            this.escalateField = value;
        }
    }

    /// <remarks/>
    public whisperType whisper
    {
        get
        {
            return this.whisperField;
        }
        set
        {
            this.whisperField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("start-monitoring-session")]
    public startmonitoringsessionType startmonitoringsession
    {
        get
        {
            return this.startmonitoringsessionField;
        }
        set
        {
            this.startmonitoringsessionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("terminate-monitoring-session")]
    public terminatemonitoringsessionType terminatemonitoringsession
    {
        get
        {
            return this.terminatemonitoringsessionField;
        }
        set
        {
            this.terminatemonitoringsessionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int requestId
    {
        get
        {
            return this.requestIdField;
        }
        set
        {
            this.requestIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sessionId
    {
        get
        {
            return this.sessionIdField;
        }
        set
        {
            this.sessionIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("response", Namespace = "", IsNullable = false)]
public partial class responseType
{

    private int requestIdField;

    private string resultField;

    private string sessionIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int requestId
    {
        get
        {
            return this.requestIdField;
        }
        set
        {
            this.requestIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sessionId
    {
        get
        {
            return this.sessionIdField;
        }
        set
        {
            this.sessionIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("notification", Namespace = "", IsNullable = false)]
public partial class notificationType
{

    private agentType[] agentinfosField;

    private string[] agentsremovedField;

    private participantType[] participantinfosField;

    private string[] partcicipantsremovedField;

    private string sessionIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("agent-infos")]
    [System.Xml.Serialization.XmlArrayItemAttribute("agent-info", IsNullable = false)]
    public agentType[] agentinfos
    {
        get
        {
            return this.agentinfosField;
        }
        set
        {
            this.agentinfosField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("agents-removed")]
    [System.Xml.Serialization.XmlArrayItemAttribute("uri", IsNullable = false)]
    public string[] agentsremoved
    {
        get
        {
            return this.agentsremovedField;
        }
        set
        {
            this.agentsremovedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("participant-infos")]
    [System.Xml.Serialization.XmlArrayItemAttribute("participant-info", IsNullable = false)]
    public participantType[] participantinfos
    {
        get
        {
            return this.participantinfosField;
        }
        set
        {
            this.participantinfosField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("partcicipants-removed")]
    [System.Xml.Serialization.XmlArrayItemAttribute("uri", IsNullable = false)]
    public string[] partcicipantsremoved
    {
        get
        {
            return this.partcicipantsremovedField;
        }
        set
        {
            this.partcicipantsremovedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sessionId
    {
        get
        {
            return this.sessionIdField;
        }
        set
        {
            this.sessionIdField = value;
        }
    }
}
