

/******************************************************************************
*                                                       *
*   Copyright (C) Microsoft. All rights reserved.   *
*                                                       *
*******************************************************************************/


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Microsoft.Rtc.Collaboration.Samples.ContactCenter.Common
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/QueueUriMapping.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("queueUriMappingList", Namespace = "http://tempuri.org/QueueUriMapping.xsd", IsNullable = false)]
    public partial class queueUriMappingListType
    {

        private queueUriMappingType[] queueUriMappingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("queueUriMapping", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public queueUriMappingType[] queueUriMapping
        {
            get
            {
                return this.queueUriMappingField;
            }
            set
            {
                this.queueUriMappingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/QueueUriMapping.xsd")]
    public partial class queueUriMappingType
    {

        private string queueNameField;

        private string uriValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queueName
        {
            get
            {
                return this.queueNameField;
            }
            set
            {
                this.queueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uriValue
        {
            get
            {
                return this.uriValueField;
            }
            set
            {
                this.uriValueField = value;
            }
        }
    }
}
